#!/home/kitral/anaconda2/bin/python2.7
import re
import subprocess

try:
    import Tkinter as tk
except ImportError:
    # Python3
    import tkinter as tk

def sendmessage(message):
    subprocess.Popen(['notify-send', message])
    return

def get_clip_text():
    root = tk.Tk()
    # keep the window from showing
    root.withdraw()
    return root.clipboard_get()

def filter_text(text):
    return text.strip()
    if len(text) > 30:
        return None
    else:
        return text.strip()

def save_text_in_file(text, file_path):
    f = open(file_path, 'aw')
    f.write(text + '\n')
    f.close()

file_path = '/home/kitral/Documents/new_sentences.txt'
text = get_clip_text()
new_text = filter_text(text)
if new_text:
    save_text_in_file(new_text, file_path)
    sendmessage("add ok")
